MVCEgitim/Controllers/MVC12SessionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCEgitim.Models; //* UyeContext namespace
using MVCEgitim.Extensions;  //* Bunuda manuel olarak ekledik.


namespace MVCEgitim.Controllers
{
    public class MVC12SessionController : Controller
    {
        private readonly UyeContext _context;

        public MVC12SessionController(UyeContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SessionOlustur(string kullaniciAdi, string sifre)
        {
            var kullanici = _context.Uyeler.FirstOrDefault(u =>
                u.KullaniciAdi == kullaniciAdi && u.Sifre == sifre
            );
            if (kullanici != null)
            {
                HttpContext.Session.SetString("kullanici", kullaniciAdi);//* sessionda Setstring metoduyla string tipinde veri saklayabiliriz.
                HttpContext.Session.SetString("sifre", sifre);
                HttpContext.Session.SetInt32("IsLoggedIn", 1);//* Sessionda SetInt32 metoduyla int tipinde veri saklayabiliriz.
                HttpContext.Session.SetString("userguid", Guid.NewGuid().ToString());
                HttpContext.Session.SetJson("uye", kullanici);//* Kendi yazdığımız set Json metoduna çektiğimiz kullanıcıyı json olarak yükle


                return RedirectToAction("SessionOku"); //* işlem başarılıysa SessionOku sayfasına git
            }
            else
            {
                TempData["Mesaj"] = @"<div class ='alert alert-danger'> Giriş Başarısız  </div>";
            }
            return View("Index");
        }

        public IActionResult SessionOku()
        {
            return View();
        }
        [HttpPost]
         public IActionResult SessionSil()
        {
            HttpContext.Session.Remove("userguid");//* userguid isimli session ı sil
             HttpContext.Session.Clear();//* Tüm sessionları sil
             return RedirectToAction("Index");
        }
    }
}

MVCEgitim/Controllers/MVC15FiltersUsingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims; //oturum açmak için gerekli
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication; //* oturum açmak için gerekli
using Microsoft.AspNetCore.Authorization; //Authorize attributeünü kullanmak için
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCEgitim.Filters; //yazdığımız filtrenin usingi buraya ekliyoruz.
using MVCEgitim.Models;

namespace MVCEgitim.Controllers
{
    public class MVC15FiltersUsingController : Controller
    {
        private readonly UyeContext _context;

        public MVC15FiltersUsingController(UyeContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [UserControl] //FiltreKullanimi Action ı çalıştığında usercontrol çalışır
        public IActionResult FiltreKullanimi()
        {
            return View();
        }

        [Authorize] //* Authorize attribute ü altındaki action ı oturum açılmamışsa korur ve ekrarnın açılmasını engeller.
        public IActionResult UyeGuncelle(int? id)
        {
            if (id == null) // eğer adres çubuğundan id gönderilmezse
            {
                return BadRequest(); //* geriye geçersiz istek hatası döndür.
            }
            Uye uye = _context.Uyeler.Find(id); // gönderilen id ye göre veritabanında arama yap
            if (uye == null) //* eğer db de kayıt bulamazsan
                return NotFound(); //* geriye not found - kayıt bulunamadı ekranı göster.
            return View(uye);
        }

        [HttpPost]
        [Authorize]
        public IActionResult UyeGuncelle(int? id, Uye uye)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Uyeler.Update(uye);
                    _context.SaveChanges();
                }
                catch (System.Exception hata)
                {
                    ModelState.AddModelError("", "Hata Oluştu!" + hata.Message);
                }
            }

            return View(uye);
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LoginAsync(Uye uye)
        {
            try
            {
                Uye admin = _context.Uyeler.FirstOrDefault(u =>
                    u.Email == uye.Email && u.Sifre == uye.Sifre
                ); //1.Yöntem
                if (admin is not null)
                {
                    //*Kullanıcıya giriş için vermek istediğimiz hakları tanımlıyoruz.
                    var haklar = new List<Claim>()
                    {
                        new Claim(ClaimTypes.Email, admin.Email),
                        new Claim(ClaimTypes.Role, "Admin"),
                    };
                    //*Kullanıcıya kimlik tanımlıyoruz.
                    var kullaniciKimligi = new ClaimsIdentity(haklar, "Login"); //* Kullanıcıya tanımladığımız hakları kimliğe işliyoruz.
                    //*Kullanıcıya verdiğimiz kimlik ile tanımlı kurallardan oluşan nesne oluşturuyoruz.
                    ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(kullaniciKimligi); //* Yetkilendirme ile sismeye giriş yapıyoruz.
                    await HttpContext.SignInAsync(claimsPrincipal);
                    //*Giriş sonrası tarayıcıda return url varsa
                    if (!string.IsNullOrEmpty(HttpContext.Request.Query["ReturnUrl"]))
                    {
                        return Redirect(HttpContext.Request.Query["ReturnUrl"]); //kullanıcıyı ReturnUrl deki gitmek istediği adrese yönlendir.
                    }
                    return RedirectToAction("Index"); //ReturnUrl yoksa anasayfaya yönlendir.
                }
            }
            catch (System.Exception hata)
            {
                ModelState.AddModelError("", "Hata Oluştu!" + hata.Message);
            }
            ModelState.AddModelError("", "Giriş Başarısız");
            return View(uye);
        }
        [HttpPost] 
         public IActionResult Logout()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Index");
        }
    }
}

MVCEgitim/Views/MVC15FiltersUsing/FiltreKullanimi.cshtml
@using MVCEgitim.Extensions;
@{
    ViewBag.Title = "MVC15 Filters Using";
    var uye = Context.Session.GetJson<Uye>("uye");
        
}

<h2>Filtre Kullanimi</h2>
<p>
    Bu ekrana Filtredeki gibi oturum açılırsa erişilebilir.
</p>
@if(Context.Session.GetInt32("IsLoggedIn") ==1) //*Kullanıcı girişi yapıldığında oluşturduğumuz IsLoggedIn isimli session ı kontrol et. Değeri 1 ise
{
<h3> Hoşgeldin Paşam : @Context.Session.GetString("kullanici")</h3>
<h3> Guid : @Context.Session.GetString("userguid")</h3>

    if(uye is not null)
    {
        <table class= "table">
            <tr>
                <td>Ad Soyad</td>
                <td>@uye.Ad. @uye.Soyad</td>
            </tr>
              <tr>
                <td>Email</td>
                <td>@uye.Email</td>
            </tr>
              <tr>
                <td>TC Kimlik No</td>
                <td>@uye.TcKimlikNo</td>
            </tr>
              <tr>
                <td>Telefon</td>
                <td>@uye.Telefon</td>
            </tr>
              <tr>
                <td>Doğum Tarihi</td>
                <td>@uye.DogumTarihi</td>
            </tr>
        </table>
    }
<form  asp-controller="MVC12Session" asp-action = "SessionSil">
    <input type="submit" value="Oturum Kapat" class="btn btn-danger" />
</form>
}

MVCEgitim/Views/MVC15FiltersUsing/Index.cshtml
@{
    ViewBag.Title = "MVC15 Filters Using";
   
}

<h2>MVC de uygulamaya yapılıcak istekler için hazır filtreler bulunmaktadır. <br>
Bununla beraber kendi filtrelerimizi de oluşturabilmekteyiz.</h2>

<a href="/MVC15FiltersUsing/FiltreKullanimi"> Filtre Kullanımı</a>



<h2>Authorize Filter</h2>

<p class="alert alert-danger">
    Admin paneli görei gören ekranlarda crud işlemleri yapılıyorsa güvenliği sağlamak için kullanılan bir .net bileşenidir.a
    <br>
    Korumaya almak istediğimiz action veya controllen ın üzerine ekleyerek kullanabiliriz.
    <br>
    Ayrıca Program.cs dosyasına authentication kodlarını eklememiz gerekir.
</p>

<a href="/MVC15FiltersUsing/UyeGuncelle/1004">Uye Guncelle</a>

MVCEgitim/Views/MVC15FiltersUsing/Login.cshtml
   
@model Uye
 
@{

    ViewData["Title"] = "Üye Girişi";

}
 
<h1>Üye Girişi</h1>
 


<hr />

<div class="row">

    <div class="col-md-4">

        <form asp-action="Login">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            

           

            <div class="form-group">

                <label asp-for="Email" class="control-label"></label>

                <input asp-for="Email" class="form-control" />

                <span asp-validation-for="Email" class="text-danger"></span>

            </div>

           
            <div class="form-group">

                <label asp-for="Sifre" class="control-label"></label>

                <input asp-for="Sifre" class="form-control" />

                <span asp-validation-for="Sifre" class="text-danger"></span>

            </div>

           

            <div class="form-group mt-3">

                <input type="submit" value="Giriş" class="btn btn-primary" />

            </div>

        </form>

    </div>

</div>
 

MVCEgitim/Views/MVC15FiltersUsing/UyeGuncelle.cshtml
   
@model Uye
 
@{

    ViewData["Title"] = "Üye Düzenle";

}
 
<h1>Üye Düzenle</h1>
 <form asp-action = "Logout" class="text-end">
    <input type="submit" value="Oturumu Kapat" class="btn btn-danger">
 </form>
<h4>Üye Bilgileri</h4>

<hr />

<div class="row">

    <div class="col-md-4">

        <form asp-action="UyeGuncelle">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />

            <div class="form-group">

                <label asp-for="Ad" class="control-label"></label>

                <input asp-for="Ad" class="form-control" />

                <span asp-validation-for="Ad" class="text-danger"></span>

            </div>

            <div class="form-group">

                <label asp-for="Soyad" class="control-label"></label>

                <input asp-for="Soyad" class="form-control" />

                <span asp-validation-for="Soyad" class="text-danger"></span>

            </div>

            <div class="form-group">

                <label asp-for="Email" class="control-label"></label>

                <input asp-for="Email" class="form-control" />

                <span asp-validation-for="Email" class="text-danger"></span>

            </div>

            <div class="form-group">

                <label asp-for="Telefon" class="control-label"></label>

                <input asp-for="Telefon" class="form-control" />

                <span asp-validation-for="Telefon" class="text-danger"></span>

            </div>

            <div class="form-group">

                <label asp-for="TcKimlikNo" class="control-label"></label>

                <input asp-for="TcKimlikNo" class="form-control" />

                <span asp-validation-for="TcKimlikNo" class="text-danger"></span>

            </div>

            <div class="form-group">

                <label asp-for="KullaniciAdi" class="control-label"></label>

                <input asp-for="KullaniciAdi" class="form-control" />

                <span asp-validation-for="KullaniciAdi" class="text-danger"></span>

            </div>

            <div class="form-group">

                <label asp-for="Sifre" class="control-label"></label>

                <input asp-for="Sifre" class="form-control" />

                <span asp-validation-for="Sifre" class="text-danger"></span>

            </div>

            <div class="form-group">

                <label asp-for="SifreTekrar" class="control-label"></label>

                <input asp-for="SifreTekrar" class="form-control" />

                <span asp-validation-for="SifreTekrar" class="text-danger"></span>

            </div>

            <div class="form-group">

                <label asp-for="DogumTarihi" class="control-label"></label>

                <input asp-for="DogumTarihi" class="form-control" />

                <span asp-validation-for="DogumTarihi" class="text-danger"></span>

            </div>

            <div class="form-group mt-3">

                <input type="submit" value="Kaydet" class="btn btn-primary" />

            </div>

        </form>

    </div>

</div>
 
<div>

    <a asp-action="Index">Listeye Dön</a>

</div>
 